# Generated by Django 6.0.4 on 2026-04-21 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0005_alter_facility_facility_type'),
        ('stock', '0005_alter_transaction_reference_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(blank=True, help_text='Leave blank to auto-generate (e.g., ALK-2025-0042)', max_length=100, unique=True)),
                ('referensi', models.CharField(blank=True, help_text='Nomor referensi (BAST, SP, dll.)', max_length=255)),
                ('allocation_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('APPROVED', 'Disetujui'), ('PARTIALLY_FULFILLED', 'Sebagian Terpenuhi'), ('FULFILLED', 'Terpenuhi'), ('REJECTED', 'Ditolak')], default='DRAFT', max_length=25)),
                ('rejection_reason', models.TextField(blank=True, help_text='Alasan penolakan dari Kepala Instalasi')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_allocations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_allocations', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_allocations', to=settings.AUTH_USER_MODEL)),
                ('sumber_dana', models.ForeignKey(help_text='Sumber dana alokasi (APBD, Hibah, Kemenkes, dll.)', on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='items.fundingsource')),
            ],
            options={
                'db_table': 'allocations',
                'ordering': ['-allocation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_facilities', to='allocation.allocation')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_selections', to='items.facility')),
            ],
            options={
                'db_table': 'allocation_facilities',
                'ordering': ['facility__name'],
            },
        ),
        migrations.CreateModel(
            name='AllocationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_qty_available', models.DecimalField(decimal_places=2, default=0, help_text='Snapshot of available stock at draft time', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='allocation.allocation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_items', to='items.item')),
                ('stock', models.ForeignKey(blank=True, help_text='Specific batch allocated (FEFO selection)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocation_items', to='stock.stock')),
            ],
            options={
                'db_table': 'allocation_items',
                'ordering': ['item__nama_barang'],
            },
        ),
        migrations.CreateModel(
            name='AllocationItemFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_allocated', models.DecimalField(decimal_places=2, help_text='Quantity allocated to this facility (locked after approval)', max_digits=12)),
                ('allocation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_allocations', to='allocation.allocationitem')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_item_facilities', to='items.facility')),
            ],
            options={
                'db_table': 'allocation_item_facilities',
                'ordering': ['facility__name'],
            },
        ),
        migrations.CreateModel(
            name='AllocationStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='allocation.allocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_staff_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'allocation_staff_assignments',
                'ordering': ['user__full_name', 'user__username'],
            },
        ),
        migrations.AddIndex(
            model_name='allocation',
            index=models.Index(fields=['status', 'allocation_date'], name='idx_alloc_status_date'),
        ),
        migrations.AlterUniqueTogether(
            name='allocationfacility',
            unique_together={('allocation', 'facility')},
        ),
        migrations.AlterUniqueTogether(
            name='allocationitemfacility',
            unique_together={('allocation_item', 'facility')},
        ),
        migrations.AlterUniqueTogether(
            name='allocationstaffassignment',
            unique_together={('allocation', 'user')},
        ),
    ]
