# Generated by Django 6.0.2 on 2026-04-20 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0005_alter_facility_facility_type"),
        ("stock", "0004_alter_transaction_reference_type_stocktransfer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Allocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_number", models.CharField(blank=True, help_text="Leave blank to auto-generate (e.g., ALC-YYYYMM-XXXXX)", max_length=100, unique=True)),
                ("allocation_date", models.DateField()),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("SUBMITTED", "Diajukan"), ("APPROVED", "Disetujui"), ("PREPARED", "Disiapkan"), ("DISTRIBUTED", "Terdistribusi"), ("REJECTED", "Ditolak")], default="DRAFT", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("prepared_at", models.DateTimeField(blank=True, null=True)),
                ("distributed_at", models.DateTimeField(blank=True, null=True)),
                ("distributed_date", models.DateField(blank=True, null=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="approved_allocations", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_allocations", to=settings.AUTH_USER_MODEL)),
                ("distributed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="distributed_allocations", to=settings.AUTH_USER_MODEL)),
                ("prepared_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="prepared_allocations", to=settings.AUTH_USER_MODEL)),
                ("submitted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="submitted_allocations", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "allocations",
                "ordering": ["-allocation_date", "-created_at"],
                "indexes": [models.Index(fields=["status", "allocation_date"], name="idx_alloc_status_date")],
            },
        ),
        migrations.CreateModel(
            name="AllocationFacility",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("allocation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="selected_facilities", to="allocation.allocation")),
                ("facility", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="allocation_selections", to="items.facility")),
            ],
            options={
                "db_table": "allocation_facilities",
                "ordering": ["facility__name"],
                "unique_together": {("allocation", "facility")},
            },
        ),
        migrations.CreateModel(
            name="AllocationItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("issued_batch_lot", models.CharField(blank=True, max_length=100)),
                ("issued_expiry_date", models.DateField(blank=True, null=True)),
                ("issued_unit_price", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("allocation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="allocation.allocation")),
                ("facility", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="allocation_items", to="items.facility")),
                ("issued_sumber_dana", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="issued_allocation_items", to="items.fundingsource")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="allocation_items", to="items.item")),
                ("stock", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="allocation_items", to="stock.stock")),
            ],
            options={
                "db_table": "allocation_items",
                "ordering": ["facility__name", "item__nama_barang"],
            },
        ),
        migrations.CreateModel(
            name="AllocationStaffAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("allocation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="staff_assignments", to="allocation.allocation")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="allocation_staff_assignments", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "allocation_staff_assignments",
                "ordering": ["user__full_name", "user__username"],
                "unique_together": {("allocation", "user")},
            },
        ),
    ]
