# Generated by Django 6.0.2 on 2026-04-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_alter_transaction_reference_type_stocktransfer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="reference_type",
            field=models.CharField(
                choices=[
                    ("RECEIVING", "Penerimaan"),
                    ("DISTRIBUTION", "Distribusi"),
                    ("ALLOCATION", "Alokasi"),
                    ("ADJUSTMENT", "Penyesuaian"),
                    ("INITIAL_IMPORT", "Import Awal"),
                    ("RECALL", "Recall"),
                    ("EXPIRED", "Kedaluwarsa"),
                    ("TRANSFER", "Mutasi Lokasi"),
                ],
                max_length=20,
            ),
        ),
    ]