# Generated by Django 6.0.2 on 2026-03-31 02:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0004_distributionstaffassignment'),
        ('items', '0004_add_program_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuskesmasRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(blank=True, help_text='Kosongkan untuk auto-generate (REQ-YYYYMM-XXXXX)', max_length=100, unique=True)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_puskesmas_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_puskesmas_requests', to=settings.AUTH_USER_MODEL)),
                ('distribution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puskesmas_request', to='distribution.distribution')),
                ('facility', models.ForeignKey(limit_choices_to={'facility_type': 'PUSKESMAS', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='puskesmas_requests', to='items.facility')),
                ('program', models.ForeignKey(blank=True, help_text='Program kesehatan terkait (opsional, e.g. TB, HIV, Malaria)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puskesmas_requests', to='items.program')),
            ],
            options={
                'db_table': 'puskesmas_requests',
                'ordering': ['-request_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PuskesmasRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.DecimalField(decimal_places=2, help_text='Jumlah yang diminta', max_digits=12)),
                ('quantity_approved', models.DecimalField(blank=True, decimal_places=2, help_text='Jumlah yang disetujui (diisi saat approval)', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puskesmas_request_items', to='items.item')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='puskesmas.puskesmasrequest')),
            ],
            options={
                'db_table': 'puskesmas_request_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='puskesmasrequest',
            index=models.Index(fields=['status', 'request_date'], name='idx_pkreq_status_date'),
        ),
        migrations.AddIndex(
            model_name='puskesmasrequest',
            index=models.Index(fields=['facility', 'request_date'], name='idx_pkreq_facility_date'),
        ),
    ]
