# Generated by Django 6.0.2 on 2026-03-31 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_add_program_model'),
        ('users', '0006_alter_moduleaccess_module_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='For PUSKESMAS role: the facility this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operators', to='items.facility'),
        ),
        migrations.AlterField(
            model_name='moduleaccess',
            name='module',
            field=models.CharField(choices=[('users', 'Manajemen User'), ('items', 'Master Barang'), ('stock', 'Stok'), ('receiving', 'Penerimaan'), ('distribution', 'Distribusi'), ('recall', 'Recall / Retur'), ('expired', 'Kadaluarsa'), ('stock_opname', 'Stock Opname'), ('reports', 'Laporan'), ('admin_panel', 'Admin Panel'), ('puskesmas', 'Permintaan Puskesmas'), ('lplpo', 'LPLPO')], max_length=30),
        ),
    ]
