# Generated by Django 6.0.2 on 2026-04-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_facility_alter_moduleaccess_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moduleaccess",
            name="module",
            field=models.CharField(
                choices=[
                    ("users", "Manajemen User"),
                    ("items", "Master Barang"),
                    ("stock", "Stok"),
                    ("receiving", "Penerimaan"),
                    ("distribution", "Distribusi"),
                    ("allocation", "Alokasi"),
                    ("recall", "Recall / Retur"),
                    ("expired", "Kadaluarsa"),
                    ("stock_opname", "Stock Opname"),
                    ("reports", "Laporan"),
                    ("admin_panel", "Admin Panel"),
                    ("puskesmas", "Permintaan Puskesmas"),
                    ("lplpo", "LPLPO"),
                ],
                max_length=30,
            ),
        ),
    ]