# Generated by Django 6.0.2 on 2026-04-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility_name', models.CharField(default='Healthcare Inventory Management System', max_length=255)),
                ('facility_address', models.TextField(blank=True)),
                ('facility_phone', models.CharField(blank=True, max_length=50)),
                ('header_title', models.CharField(default='KEMENTERIAN KESEHATAN REPUBLIK INDONESIA', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Biarkan kosong jika tidak ada logo khusus. Gunakan gambar transparan (PNG) untuk hasil terbaik.', null=True, upload_to='settings/')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
