# Generated by Django 6.0.2 on 2026-04-09 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_distributionitem_issued_batch_lot_and_more'),
        ('items', '0005_alter_facility_facility_type'),
        ('receiving', '0006_receivingtypeoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Required for Pengembalian RS type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivings', to='items.facility'),
        ),
        migrations.AddField(
            model_name='receivingitem',
            name='settlement_distribution_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settlement_receipts', to='distribution.distributionitem'),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='receiving_type',
            field=models.CharField(choices=[('PROCUREMENT', 'Pengadaan'), ('GRANT', 'Hibah'), ('RETURN_RS', 'Pengembalian RS')], max_length=20),
        ),
    ]
