# Generated by Django 6.0.2 on 2026-04-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expired', '0002_add_disposed_audit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expired',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('VERIFIED', 'Terverifikasi'), ('DISPOSED', 'Keluar dari Stock')], default='DRAFT', max_length=20),
        ),
    ]
