# Generated by Django 6.0.2 on 2026-04-09 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_distributionstaffassignment'),
        ('items', '0005_alter_facility_facility_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionitem',
            name='issued_batch_lot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='distributionitem',
            name='issued_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionitem',
            name='issued_sumber_dana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_distribution_items', to='items.fundingsource'),
        ),
        migrations.AddField(
            model_name='distributionitem',
            name='issued_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='distribution_type',
            field=models.CharField(choices=[('LPLPO', 'LPLPO'), ('ALLOCATION', 'Alokasi'), ('SPECIAL_REQUEST', 'Permintaan Khusus'), ('BORROW_RS', 'Pinjam RS'), ('SWAP_RS', 'Tukar RS')], max_length=20),
        ),
    ]
