# Generated by Django 6.0.4 on 2026-04-21 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
        ('distribution', '0005_distributionitem_issued_batch_lot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='allocation',
            field=models.ForeignKey(blank=True, help_text='Parent allocation that auto-generated this distribution', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='allocation.allocation'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='distribution_type',
            field=models.CharField(choices=[('LPLPO', 'LPLPO'), ('ALLOCATION', 'Alokasi'), ('SPECIAL_REQUEST', 'Permintaan Khusus')], max_length=20),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('VERIFIED', 'Terverifikasi'), ('GENERATED', 'Dibuat Otomatis'), ('PREPARED', 'Disiapkan'), ('DISTRIBUTED', 'Terdistribusi'), ('REJECTED', 'Ditolak')], default='DRAFT', max_length=20),
        ),
    ]
