# Generated by Django 6.0.4 on 2026-04-28 03:54

from django.db import migrations


def migrate_generated_to_verified(apps, schema_editor):
    """Convert any existing GENERATED distributions to VERIFIED."""
    Distribution = apps.get_model("distribution", "Distribution")
    Distribution.objects.filter(status="GENERATED").update(status="VERIFIED")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0006_distribution_allocation_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_generated_to_verified,
            reverse_code=noop,
        ),
    ]
