# Generated by Django 6.0.5 on 2026-05-18

from django.db import migrations, models


def backfill_negative_actual_quantity(apps, schema_editor):
    StockOpnameItem = apps.get_model("stock_opname", "StockOpnameItem")
    StockOpnameItem.objects.filter(actual_quantity__lt=0).update(actual_quantity=None)


class Migration(migrations.Migration):

    dependencies = [
        ("stock_opname", "0002_stockopname_assigned_to_stockopname_categories"),
    ]

    operations = [
        migrations.RunPython(
            backfill_negative_actual_quantity,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="stockopnameitem",
            constraint=models.CheckConstraint(
                condition=models.Q(actual_quantity__gte=0)
                | models.Q(actual_quantity__isnull=True),
                name="chk_stock_opname_actual_quantity_gte_0",
            ),
        ),
    ]
