# Generated by Django 6.0.2 on 2026-03-31 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0004_distributionstaffassignment'),
        ('items', '0004_add_program_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LPLPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bulan', models.PositiveSmallIntegerField(help_text='Bulan periode LPLPO (1-12)')),
                ('tahun', models.PositiveIntegerField(help_text='Tahun periode LPLPO')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan'), ('REVIEWED', 'Ditinjau'), ('DISTRIBUTED', 'Didistribusikan'), ('CLOSED', 'Ditutup')], default='DRAFT', max_length=20)),
                ('document_number', models.CharField(blank=True, help_text='Auto-generated: LPLPO-YYYYMM-XXXXX', max_length=100, unique=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_lplpos', to=settings.AUTH_USER_MODEL)),
                ('distribution', models.OneToOneField(blank=True, help_text='Distribution document generated from this LPLPO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lplpo_source', to='distribution.distribution')),
                ('facility', models.ForeignKey(limit_choices_to={'facility_type': 'PUSKESMAS', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='lplpos', to='items.facility')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_lplpos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lplpos',
                'ordering': ['-tahun', '-bulan', 'facility__name'],
            },
        ),
        migrations.CreateModel(
            name='LPLPOItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_awal', models.DecimalField(decimal_places=2, default=0, help_text='Manual on first LPLPO, auto-filled from previous month Stock Keseluruhan', max_digits=12)),
                ('penerimaan', models.DecimalField(decimal_places=2, default=0, help_text='Auto-filled from Distribution records, confirmable by Puskesmas', max_digits=12)),
                ('pemakaian', models.DecimalField(decimal_places=2, default=0, help_text='Filled by Puskesmas operator', max_digits=12)),
                ('stock_gudang_puskesmas', models.DecimalField(decimal_places=2, default=0, help_text='Physical count of Puskesmas warehouse stock', max_digits=12)),
                ('waktu_kosong', models.DecimalField(decimal_places=2, default=0, help_text='Stockout days in the reporting period', max_digits=6)),
                ('permintaan_jumlah', models.DecimalField(decimal_places=2, default=0, help_text='Requested quantity by Puskesmas', max_digits=12)),
                ('permintaan_alasan', models.TextField(blank=True, help_text='Reason for request')),
                ('persediaan', models.DecimalField(decimal_places=2, default=0, help_text='stock_awal + penerimaan', max_digits=12)),
                ('stock_keseluruhan', models.DecimalField(decimal_places=2, default=0, help_text='persediaan - pemakaian', max_digits=12)),
                ('stock_optimum', models.DecimalField(decimal_places=2, default=0, help_text='stock_keseluruhan * 1.2', max_digits=12)),
                ('jumlah_kebutuhan', models.DecimalField(decimal_places=2, default=0, help_text='(stock_keseluruhan * 0.2) + waktu_kosong', max_digits=12)),
                ('pemberian_jumlah', models.DecimalField(blank=True, decimal_places=2, help_text='Actual quantity given, system-suggested = jumlah_kebutuhan', max_digits=12, null=True)),
                ('pemberian_alasan', models.TextField(blank=True, help_text='Reason if pemberian differs from permintaan')),
                ('penerimaan_auto_filled', models.BooleanField(default=False, help_text='True if penerimaan was auto-filled from Distribution records')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lplpo_items', to='items.item')),
                ('lplpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lplpo.lplpo')),
            ],
            options={
                'db_table': 'lplpo_items',
                'ordering': ['item__kategori__sort_order', 'item__nama_barang'],
            },
        ),
        migrations.AddIndex(
            model_name='lplpo',
            index=models.Index(fields=['facility', 'tahun', 'bulan'], name='idx_lplpo_facility_period'),
        ),
        migrations.AddIndex(
            model_name='lplpo',
            index=models.Index(fields=['status'], name='idx_lplpo_status'),
        ),
        migrations.AddConstraint(
            model_name='lplpo',
            constraint=models.UniqueConstraint(fields=('facility', 'bulan', 'tahun'), name='uq_lplpo_facility_period'),
        ),
        migrations.AlterUniqueTogether(
            name='lplpoitem',
            unique_together={('lplpo', 'item')},
        ),
    ]
